### ISSUE TITLE
desktopBrowser and websocket PlotTargets do not work on (some?) Linux distributions

### ISSUE THREAD

**Issue by axb21** [Quafadas/dedav4s#14]
The problem is here:

https://github.com/Quafadas/dedav4s/blob/500d75c254bd5fdfcd190ba8efd4f95176510e07/src/main/scala/viz/PlotTarget.scala#L93

BROWSE is not supported under some Linux distributions and the `Desktop.getDesktop().browse` call throws an exception `java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!`. [This link](https://stackoverflow.com/questions/5226212/how-to-open-the-default-webbrowser-using-java) has some suggestions for cross-platform implementations; more or less you do `runtime.exec("xdg-open " + url)` on X11-based systems (I'm not sure how to do this under Wayland).

**Comment by Quafadas** [comment]
Well, you reported my first bug, so thanks for that. Gotta admit, I was hoping that truly was a cross platform with it's java write-once-run anywhere promise and all! Naive :-) ...

DesktopBrowser
I will looking into changing this, because I would like that this does work as cross platform as possible. I don't honestly have a credible strategy for testing it however. I'll follow the stackoverflow suggestions as a "Hail Mary"... let's see.

Websockets
In the first instance we can sniff the desktop to see if it's supported. If so - great - we can open the browser, if not I'll simply leave a hint in the terminal via a println about where you could browse to, manually. That should be much more robust than the Hail Mary above. I can't see a reason this should not work. 

P.S. Thanks for having a look at the lib and reporting... sorry it was a pain!

**Comment by Quafadas** [comment]
Ummm... I think GitHub got a bit keen here . I'm not sure that commit truly fixes it!

**Comment by Quafadas** [comment]
So I still get reasonable behaviour. 
@axb21 if you had the chance to give 0.5.2 a try, I have the hope that at least the websocket part should work for you....

**Comment by axb21** [comment]
> So I still get reasonable behaviour. @axb21 if you had the chance to give 0.5.2 a try, I have the hope that at least the websocket part should work for you....

I'm not sure where to find 0.5.2:
```sbt
[error] (update) sbt.librarymanagement.ResolveException: Error downloading io.github.quafadas:dedav4s_3:0.5.2
```

I did try cloning the repository (commit 47c7f2) and building it locally. Both the desktop target and websocket target work as advertised!

A minor quibble: 
```scala
scala> List(1,4,6,7,4,4).plotBarChart()
starting local server on 18028
2022-03-07 16:53:02.563-0500  info [threads] JBoss Threads version 3.1.0.Final 
java.awt.Desktop claims the browse action is not supported in this environment. Consider opening a browser at https://localhost:18028 , where you should find your plot
requests.RequestFailedException: Request to http://localhost:18028/viz failed with status code 418
```

The error here admonishes one to open `https://localhost:18028`, with HTTPS, but the local server is using HTTP. 

Thanks for your quick attention to this! I'm looking forward to playing with it.

**Comment by axb21** [comment]
Sorry about the comment spam, but a question: couldn't the websocket target work similarly to the desktop one, and use `xdg-open` to open the browser? Versus asking the user to copy-paste a URL?

In my environment at least, `xdg-open` has nice behavior (to me anyway). If you already have a browser running, it will create a new tab with the requested URL. If you don't have a browser open, it will launch your default browser with the requested URL.

**Comment by Quafadas** [comment]
> Sorry about the comment spam, but a question: couldn't the websocket target work similarly to the desktop one, and use xdg-open to open the browser? Versus asking the user to copy-paste a URL?

Given we now know that works, I think yes. I didn't want to publish something which then didn't work for you with both targets again, so I left the websockets implementation to be more robust. It's an easy change... 

> The error here admonishes one to open https://localhost:18028, with HTTPS, but the local server is using HTTP.
Oops. Yes... will change that.

> I'm not sure where to find 0.5.2: 
It ought to be on Maven central, although sometimes that seems to take a couple of hours, so might just be a timing / sync thing.

**Comment by Quafadas** [comment]
I realised a couple of things; 
1. I messed up setting a config variable correctly, so 0.5.2 & 0.5.3 are not useable
2. I forgot to actually publish the tag, which was why you didn't find the release

So a bit of a mess, and we're up to 0.5.4, but it should work for you... with all your suggestions taken into account. Thanks for the feedback - happy plotting! Please let me know how you get on, if the paradigm works for you. 

Closing now :-).
